### ISSUE TITLE
query about insertions

### ISSUE THREAD

**Issue by prasundutta87** [ryanlayer/stix#11]
Hi,

I was wondering why insertions where left out in the paper describing STIX (_Searching thousands of genomes to classify somatic and novel structural variants using STIX_) Also, why weren't insertions compared to the population SV databases?

Regards,
Prasun

**Comment by ryanlayer** [comment]
We are still working on supporting insertions.

**Comment by prasundutta87** [comment]
Thanks for your reply @ryanlayer !
