### ISSUE TITLE
Error while running stix

### ISSUE THREAD

**Issue by KeyTals** [ryanlayer/stix#9]
Hello Ryan,

I am getting following while running stix.

stix: Could not open data file 'normals_b/cache.2045.dat'.: Too many open files

here is the command i use

stix/bin/stix -i normals_b -d normals.ped.db -s 500 -f Tonly.vcf.gz

Also this is how i creared ped.db

stix/bin/stix -i normals_b  -p normals.ped -d normals.ped.db -c 3

_PED database normals.ped.db with 10 rows created from normals.ped._

and my ped looks something like

Sample  Sex     Alt_file
normal_S1     0       normal_S1.bed.gz

Could you please help to diagnose the issue.

Thanks,
Keyur

**Comment by ryanlayer** [comment]
You need to allow more open files. Try ulimit -Sn 16384

**Comment by mchowdh200** [comment]
I know this is an old issue, but the other solution is to filter out the thousands of small contigs in some reference genomes (or during the `samtools` command that is piped to `excord`.  This will drastically reduce the number of files created by giggle during the indexing process.
